version: '2.1'
services:
  dependence_visual:
    image: "archguard/dependence_visual"
    container_name: dependence_visual
    depends_on:
      - dependence-api
      - code-analysis-addition
      - code-scanner
    ports:
      - "10081:80"
      - "11443:443"
    networks:
      - dependence_network

  
  code-analysis-addition:
    image: "archguard/backend_addition"
    container_name: code-analysis-addition
    ports:
        - "18080:8080"
    environment:
      app_env: dev
    networks:
      - dependence_network

  dependence-api:
    image: "archguard/dependence_api"
    container_name: dependence-api
    ports:
      - "18081:9000"
    environment:
      app_env: dev
    networks:
      - dependence_network

  code-scanner:
    image: "archguard/code_scanner"
    container_name: code-scanner
    mem_limit: 2048m
    memswap_limit: 2048m
    ports:
        - "18082:8080"
    environment:
      app_env: dev
    volumes:
      - "~/.m2:/root/.m2"
    healthcheck:
      test: curl -f http://localhost:8080/hello || exit 1
      timeout: 10s
      retries: 5 
    networks:
      - dependence_network

networks:
  dependence_network:

