version: '2.1'
services:
  dependence_visual:
    image: "archguard/dependence_visual"
    container_name: dependence_visual
    depends_on:
      - dependence-api
      - code-analysis-addition
      - code-scanner
    ports:
      - "10080:80"
      - "10443:443"
    networks:
      - dependence_network

  
  code-analysis-addition:
    image: "archguard/backend_addition"
    container_name: code-analysis-addition
    depends_on:
      code-scanner:
        condition: service_healthy
      dependence_mysql:
        condition: service_healthy
    ports:
        - "18080:8080"
    environment:
      app_env: local
    networks:
      - dependence_network

  dependence-api:
    image: "archguard/dependence_api"
    container_name: dependence-api
    depends_on:
      code-scanner:
        condition: service_healthy
      dependence_mysql:
        condition: service_healthy
    ports:
      - "18081:9000"
    environment:
      app_env: local
    networks:
      - dependence_network

  code-scanner:
    image: "archguard/code_scanner"
    container_name: code-scanner
    mem_limit: 2048m
    memswap_limit: 2048m
    depends_on:
      dependence_mysql:
        condition: service_healthy
    ports:
        - "18082:8080"
    environment:
      app_env: local
    volumes:
      - "~/.m2:/root/.m2"
    healthcheck:
      test: curl -f http://localhost:8080/hello || exit 1
      timeout: 10s
      retries: 5 
    networks:
      - dependence_network

  dependence_mysql:
    image: "mysql"
    container_name: dependence-mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: default@default
      TZ: Asia/Shanghai
    networks:
      - dependence_network
    volumes:
      - "~/archguard_db_data:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

networks:
  dependence_network:

