version: '2.1'
services:
  dependence_visual:
    image: "archguard/dependence_visual:prod"
    container_name: dependence_visual_prod
    depends_on:
      - code-addition
      - code-scanner
      - code-analysis
    ports:
      - "11080:80"
      - "11443:443"
    networks:
      - dependence_network_prod
  
  code-addition:
    image: "archguard/backend_addition:prod"
    container_name: code-addition-prod
    depends_on:
      code-scanner:
        condition: service_healthy
      dependence_mysql:
        condition: service_healthy
    ports:
        - "18180:8080"
    environment:
      app_env: prod
    networks:
      - dependence_network_prod
    restart: on-failure:10

  code-scanner:
    image: "archguard/code_scanner:prod"
    container_name: code-scanner-prod
    mem_limit: 2048m
    memswap_limit: 2048m
    depends_on:
      dependence_mysql:
        condition: service_healthy
      flyway-server:
        condition: service_started
    ports:
        - "18182:8080"
    environment:
      app_env: prod
    volumes:
      - "~/.m2:/root/.m2"
      - "~/.gradle:/root/.gradle"
    healthcheck:
      test: curl -f http://localhost:8080/hello || exit 1
      timeout: 10s
      retries: 5 
    networks:
      - dependence_network_prod
    restart: on-failure:10

  code-analysis:
    image: "archguard/analysis_module:prod"
    container_name: code-analysis-prod
    depends_on:
      code-scanner:
        condition: service_healthy
      dependence_mysql:
        condition: service_healthy
    ports:
      - "18183:8080"
    environment:
      app_env: prod
    networks:
      - dependence_network_prod
    restart: on-failure:10

  flyway-server:
    image: "archguard/flyway_server:prod"
    container_name: flyway-server-prod
    depends_on:
      dependence_mysql:
        condition: service_healthy
    networks:
      - dependence_network_prod

  dependence_mysql:
    image: "mysql"
    container_name: dependence-mysql-prod
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "13308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: default@default
      TZ: Asia/Shanghai
    networks:
      - dependence_network_prod
    volumes:
      - "~/archguard_db_data_prod:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  influxdb:
    image: "influxdb"
    container_name: influxdb-prod
    ports:
      - '8186:8086'
    networks:
      - dependence_network_prod
    healthcheck:
      test: curl -f http://localhost:8086/ping || exit 1
      timeout: 10s
      retries: 5
    volumes:
      - "~/archguard_influxdb_data_prod:/var/lib/influxdb"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  grafana:
    image: "grafana/grafana"
    container_name: grafana-prod
    ports:
      - '3100:3000'
    user: "root"
    volumes:
      - "~/archguard_grafana_data_prod:/var/lib/grafana"
    networks:
      - dependence_network_prod
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  dependence_network_prod:

